{% set name = "pymemcache" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 988ea618376db3cb1291927547c6945d0c947a4dfb8436e02858ecbef12f50fc

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
    - six
  run:
    - python
    - six

test:
  imports:
    - pymemcache
    - pymemcache.client
    - pymemcache.test

about:
  home: https://github.com/Pinterest/pymemcache
  license: Apache
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A comprehensive, fast, pure Python memcached client

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
