travis:
  secure:
    BINSTAR_TOKEN: JkzvIn31CTsDMfp68+SyS88O9VD0L07rlkZasd9hjTdB3yQ93OUksc3Xc5CfbBGToMgAja9NcgIWwTz3y/zg3474meRsXbtFynRHHdAtvI6DF2x8c3Bh5CdjzfR0XN9tvEgAKYmQjGcU0kGmnpT+RaYja1Zbc38xrWILkYMYW3Ymq+2g2Uh8Bw+Vs6MNWKwGXno9U+y1HpYnFRIKuIkk7bWaU1tAePqA7xC9X256Y1IyWOgyE6HcNAg/CPlEITMalklmeetwc52Y23+2yZfwvchX98YCdFYIrb4TgQ/JeNZdwhgmKkfF/CjWr0OGwWDLbx83hDHE9SLvRdZjjqzT2Uf3dtDK2BrcPUqJe2h2XjWesnvZ+4fnYqQJMaLrg4nhWxjw/7WF8IEOotNQOZltaHQMertXJf4sNkq4pUyZsz6mXwBez790LOpEontinad5Uc4SaBcjFiqfoqBx2ztdDiCO9rGenumtFf3gyEY5oxQrBcCh8PRwP2PbBLOSKTzIHGfDHan3UjD1Jj+xBA/Ma8Pd2stqdSIHwDkHa0ECukRZ/pAZkQ/toMzx36gotLrwCh6UW8POFOWUMIbe06g7MN58mFCO6aGx5VcnBr277fzg2BobiwB9dKSK4OrFjbe07lEyB3EW7Y6aiF2gzQfXY6GNahqwPM+z0aVTFOWy6kU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
